erwindouna/python-tado

- .github/workflows/release.yaml
- pyproject.toml
> Small fixes for a release draft

- .github/workflows/release.yaml
> Updating release.yaml

- .github/workflows/release-test.yaml
> Adding Pypi test

- pyproject.toml
> Adding name to top

- .github/workflows/release.yaml
> Adding work dispatch

- README.md
> Updating project description in readme

- pyproject.toml
- src/tadoasync/models.py
- tests/__snapshots__/test_tado.ambr
> Include mobile settings

- README.md
- src/tadoasync/models.py
- tests/__snapshots__/test_tado.ambr
- tests/fixtures/mobile_devices.json
> Add mobile location

- pyproject.toml
- src/tadoasync/tadoasync.py
- tests/test_tado.py
> Refactor the session and login mechanism

- src/tadoasync/tadoasync.py
- tests/__snapshots__/test_tado.ambr
- tests/test_tado.py
> Include geofencing support function

- docs/requirements.txt
- docs/source/api.rst
- poetry.lock
> Extend readthedocs

- .readthedocs.yaml
- poetry.lock
- pyproject.toml
> Include the requirements

- .readthedocs.yaml
- docs/source/api.rst
> Small adjustments

- docs/source/conf.py
> Change path

- .readthedocs.yaml
- docs/source/conf.py
> Refactor the path

- .readthedocs.yaml
> Change method of readthedocs

- README.md
> Update readme to readthedocs badge

- docs/source/index.rst
- docs/source/models.rst
> Incude models

- docs/source/models.rst
> Expand the models

- pyproject.toml
> Upgrade to version 0.1.14

- poetry.lock
- pyproject.toml
- src/tadoasync/tadoasync.py
> Creating new version

- README.md
- src/tadoasync/tadoasync.py
- tests/test_tado.py
> Refactor check status & minor adjustments

- pyproject.toml
- src/tadoasync/tadoasync.py
- tests/test_tado.py
> Preparing steps for HA integration

- .github/workflows/release.yaml
> Update sigstore & PyPI

- src/tadoasync/models.py
- src/tadoasync/tadoasync.py
- tests/__snapshots__/test_tado.ambr
So with `dict[Any, Any]` there it would never fail and always serialize, but it would be harder to use
> Make sure we don't serialize as dict
